Typo
By the way, the sampling() does not work:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) :
  Exception: variable does not exist; processing stage=data initialization; variable name=N; base type=int  (in 'model6d34530f74d5_lotka_volterra' at line 21)

failed to create the sampler; sampling not done